languageCode = "en-us"
title = "Arman Anwar -- Lost in Space"
theme = "lembas"
googleAnalytics = ""
disqusShortname = ""

[socialMedia]
  gitHub = "https://github.com/armaninspace"
  linkedIn = "https://www.linkedin.com/in/arman-anwar-a107961/"
  twitter = "https://twitter.com/armaninspace"


[[dropDownMenu]]
  name = "About"
  url = "/content/pages/about"
[[dropDownMenu]]
  name = "Blogs"
  url = "/content/pages/blogs"

[params]
    description = ""
    [params.logo]
    url = "A-logo.svg"
    width = 50
    height = 50
    alt = "Logo"

