---
title: "About Arman Anwar"
---

With over two decades of building innovative technological solutions that have solved some of the most seemingly intractable problems of the information age, Arman is in a league of his own. He holds two Masters degrees in Computer Science and Software Systems Engineering from George Mason University with an emphasis on Artificial Intelligence. He has pursued graduate work in Statistical Machine Learning at Stanford University,

In addition to speaking dozens of computer languages and six human languages, in his “spare time” you are as likely to find him refurbishing an abandoned Cray Supercomputer, solving puzzles in computational mathematics, or riding one of his motorcycles.

Arman has had a long-time passion for text analytics, machine learning, graph-based analytic methods, and artificial intelligence. His work has been instrumental to dramatically improving capabilities and performance for Fortune 500 companies, government agencies, international startups, and non-profits.

At AppliedAi he and his teams are the glue that binds the best analytic solutions available anywhere on the planet to platforms that are both easy to understand and operate; and effective at facilitating profitable organizational improvements.